name: couchdb-ryanjyoder
version: 2.3.0
summary: Document based database
description: CouchDB is a database that completely embraces the web. Store your data with JSON documents. Access your documents and query your indexes with your web browser, via HTTP. Index, combine, and transform your documents with JavaScript. 
confinement: strict
grade: stable
base: core

apps:
    server:
        daemon: simple
        command: rel/couchdb/bin/snap_run
        plugs: [network-bind, process-control]
        environment:
            LD_LIBRARY_PATH: $SNAP/usr/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
parts:
    couchdb: 
        plugin: make
        source: http://www-us.apache.org/dist/couchdb/source/2.3.0/apache-couchdb-2.3.0.tar.gz
        #source: https://github.com/apache/couchdb.git
        #source-type: git
        #source-tag: 2.3.0
        override-build: |
          ./configure --disable-docs
          make release
          cp -ra ./rel $SNAPCRAFT_PART_INSTALL
          cp -ra ./bin $SNAPCRAFT_PART_INSTALL
        build-packages:
          - binutils
          - libc6-dev
          - gcc
          - g++
          - make
          - erlang-dev
          - erlang-base
          - erlang-reltool
          - libcurl4-openssl-dev
          - libnspr4-dev
          - libicu-dev
          - icu-devtools
          # For erlang/rebar processing
          - erlang-nox
          - erlang-os-mon
          - erlang-syntax-tools
          # For fauxton
          - nodejs-dev
          - nodejs
          - npm
        stage:
            - rel
            - bin
        prime:
            - rel
            - bin
        after: [packages]

    snap-config:
        plugin: dump
        source: ./snap/local/
        organize:
            couchdb.ini: rel/couchdb/etc/default.d/couchdb.ini
            snap_run: rel/couchdb/bin/snap_run

    packages:
        plugin: nil
        source: .
        stage-packages:
          - libicu55
          - libnspr4
          - libicu-dev
        build-packages:
          - devscripts
          - debhelper
          - zip 
          - pkg-kde-tools 
          - pkg-config
          - libffi-dev
        override-build: |
          make couch-js-debs PLATFORM=bionic
          ls -1 js/ | grep ".deb$" | xargs -i++ dpkg -x js/++ .
          mkdir -p $SNAPCRAFT_PART_INSTALL/usr
          cp -ra ./usr/lib $SNAPCRAFT_PART_INSTALL/usr
        filesets:
            exclusion:
              - "-usr/share/doc/*"
              - "-usr/share/man/*"
        prime:
            - "$exclusion"
