name: couchdb-ryanjyoder
version: 2.3.1
summary: Official Apache CouchDB snap - a clustering document oriented database
description: |
  CouchDB is a database that completely embraces the web. Store your data with
  JSON documents. Access your documents and query your indexes with your web
  browser, via HTTP. Index, combine, and transform your documents with
  JavaScript. 


assumes: [command-chain, common-data-dir]
base: core18
grade: stable
confinement: strict

parts:
  libmozjs185:
    plugin: make
    source: .
    override-build: |
      make couch-js-debs PLATFORM=bionic
      sudo dpkg -i js/*.deb
      sudo dpkg-deb -R js/couch-libmozjs185-1.0*.deb .
      sudo mv usr $SNAPCRAFT_PART_INSTALL
    build-packages:
      - devscripts
      - debhelper
      - libffi-dev
      - libnspr4-dev
      - pkg-kde-tools 
      - pkg-config
      - zip
    stage:
      - usr
    prime:
      - usr


  couchdb: 
    after: [libmozjs185]
    plugin: make
    # source: http://www-us.apache.org/dist/couchdb/source/2.2.0/apache-couchdb-2.2.0.tar.gz
    source: https://github.com/apache/couchdb.git
    source-type: git
    #source-tag: 2.2.0
    override-build: |
      export TRAVIS=true
      ./configure --disable-docs
      make release
      cp -ra ./rel $SNAPCRAFT_PART_INSTALL
      cp -ra ./bin $SNAPCRAFT_PART_INSTALL
    build-packages:
      - binutils
      - libc6-dev
      - gcc
      - g++
      - make
      - libnspr4-dev
      - libicu-dev
      - icu-devtools
      # For fauxton
      - nodejs
      #- libssl-dev
      - libssl1.0-dev
      - npm
      - erlang-dev
      - erlang-base
      - erlang-reltool
      # For erlang/rebar processing
      - erlang-nox
      - erlang-os-mon
      - erlang-syntax-tools
    stage:
        - rel
        - bin
    prime:
        - rel
        - bin
    stage-packages:
      - ca-certificates
      - adduser
      - curl
      - debconf
      - init-system-helpers
      # - couch-libmozjs185-1.0
      - lsb-base
      - procps
      - python3
      - python3-requests
      - libcurl4
      - libgcc1
      - libicu60
      - libssl1.1
      - libtinfo5


layout:
  # Database and log files are common across upgrades
  $SNAP/opt/couchdb/data:
    bind: $SNAP_COMMON/data
  $SNAP/opt/couchdb/var/log:
    bind: $SNAP_COMMON/log
  # Local configuration files may change across upgrades
  $SNAP/opt/couchdb/etc/vm.args:
    bind-file: $SNAP_DATA/etc/vm.args
  $SNAP/opt/couchdb/etc/local.d:
    bind: $SNAP_DATA/etc/local.d
  $SNAP/opt/couchdb/etc/local.ini:
    bind-file: $SNAP_DATA/etc/local.ini
  # We do not bind default.ini or default.d/ as these are intended to be immutable
  
environment:
  COUCHDB_ARGS_FILE: ${SNAP_DATA}/etc/vm.args
  ERL_FLAGS: "-couch_ini ${SNAP}/opt/couchdb/etc/default.ini ${SNAP}/opt/couchdb/etc/default.d ${SNAP_DATA}/etc/local.ini ${SNAP_DATA}/etc/local.d"

apps:
  couchdb:
    adapter: full
    command: opt/couchdb/bin/couchdb
    plugs: [network, network-bind, process-control, mount-observe]
  server:
    daemon: simple
    adapter: full
    command: opt/couchdb/bin/couchdb
    plugs: [network, network-bind, process-control, mount-observe]
  remsh:
    command: opt/couchdb/bin/remsh
    plugs: [network, network-bind]
  couchup:
    command: opt/couchdb/bin/couchup
    plugs: [network, network-bind]
  couchjs:
    command: opt/couchdb/bin/couchjs
    plugs: [network, network-bind]
